/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegulamentoRouteImport } from './routes/regulamento'
import { Route as PatrocinadoresRouteImport } from './routes/patrocinadores'
import { Route as MapaVivoRouteImport } from './routes/mapa-vivo'
import { Route as InscricaoRouteImport } from './routes/inscricao'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AssistirRouteImport } from './routes/assistir'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulamentoRoute = RegulamentoRouteImport.update({
  id: '/regulamento',
  path: '/regulamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrocinadoresRoute = PatrocinadoresRouteImport.update({
  id: '/patrocinadores',
  path: '/patrocinadores',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaVivoRoute = MapaVivoRouteImport.update({
  id: '/mapa-vivo',
  path: '/mapa-vivo',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoRoute = InscricaoRouteImport.update({
  id: '/inscricao',
  path: '/inscricao',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistirRoute = AssistirRouteImport.update({
  id: '/assistir',
  path: '/assistir',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistir': typeof AssistirRoute
  '/faq': typeof FaqRoute
  '/inscricao': typeof InscricaoRoute
  '/mapa-vivo': typeof MapaVivoRoute
  '/patrocinadores': typeof PatrocinadoresRoute
  '/regulamento': typeof RegulamentoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistir': typeof AssistirRoute
  '/faq': typeof FaqRoute
  '/inscricao': typeof InscricaoRoute
  '/mapa-vivo': typeof MapaVivoRoute
  '/patrocinadores': typeof PatrocinadoresRoute
  '/regulamento': typeof RegulamentoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistir': typeof AssistirRoute
  '/faq': typeof FaqRoute
  '/inscricao': typeof InscricaoRoute
  '/mapa-vivo': typeof MapaVivoRoute
  '/patrocinadores': typeof PatrocinadoresRoute
  '/regulamento': typeof RegulamentoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistir'
    | '/faq'
    | '/inscricao'
    | '/mapa-vivo'
    | '/patrocinadores'
    | '/regulamento'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistir'
    | '/faq'
    | '/inscricao'
    | '/mapa-vivo'
    | '/patrocinadores'
    | '/regulamento'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/assistir'
    | '/faq'
    | '/inscricao'
    | '/mapa-vivo'
    | '/patrocinadores'
    | '/regulamento'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistirRoute: typeof AssistirRoute
  FaqRoute: typeof FaqRoute
  InscricaoRoute: typeof InscricaoRoute
  MapaVivoRoute: typeof MapaVivoRoute
  PatrocinadoresRoute: typeof PatrocinadoresRoute
  RegulamentoRoute: typeof RegulamentoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulamento': {
      id: '/regulamento'
      path: '/regulamento'
      fullPath: '/regulamento'
      preLoaderRoute: typeof RegulamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrocinadores': {
      id: '/patrocinadores'
      path: '/patrocinadores'
      fullPath: '/patrocinadores'
      preLoaderRoute: typeof PatrocinadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa-vivo': {
      id: '/mapa-vivo'
      path: '/mapa-vivo'
      fullPath: '/mapa-vivo'
      preLoaderRoute: typeof MapaVivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao': {
      id: '/inscricao'
      path: '/inscricao'
      fullPath: '/inscricao'
      preLoaderRoute: typeof InscricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistir': {
      id: '/assistir'
      path: '/assistir'
      fullPath: '/assistir'
      preLoaderRoute: typeof AssistirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistirRoute: AssistirRoute,
  FaqRoute: FaqRoute,
  InscricaoRoute: InscricaoRoute,
  MapaVivoRoute: MapaVivoRoute,
  PatrocinadoresRoute: PatrocinadoresRoute,
  RegulamentoRoute: RegulamentoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
